Authing/docs

- docs/android/component/tutorial/advanced-login.md
- docs/en/reference/sdk-for-android/component/tutorial/advanced-login.md
- docs/reference/sdk-for-android/component/tutorial/advanced-login.md
> fix advanced login document

- docs/reference-new/sdk-v5/csharp/authentication.md
- docs/reference-new/sdk-v5/java/authentication.md
- docs/reference-new/sdk-v5/node/authentication.md
> refactor: 优化 node sdk 文案

- docs/guides/connections/enterprise/wecom-agency-qrconnect/README.md
> fix: 优化企业微信代开发文案

- docs/reference-new/sdk-v5/python/authentication.md
> update: python authentication.md

- docs/en/reference/sdk-for-csharp/README.md
- docs/reference/sdk-for-csharp/README.md
> fix:修改 csharp sdk 仓库地址

- docs/reference/guard/v2/vue.md
> fix: :wheelchair: guard 在 router-view 挂载异常解决方案文档

- docs/reference-new/sdk-v5/csharp/authentication.md
> fix:修正错误描述

- docs/common/integrate-sso.md
- docs/common/spa-auth-code-snippets/advanced.md
- docs/common/spa-auth-code-snippets/initialize.md
- docs/en/common/integrate-sso.md
- docs/en/guides/basics/authenticate-first-user/use-hosted-login-page.md
- docs/guides/basics/authenticate-first-user/use-hosted-login-page.md
- docs/quickstarts/spa/angular.md
- docs/quickstarts/spa/react.md
- docs/quickstarts/spa/vue.md
更新 @authing/spa-auth-sdk 包名为 @authing/browser
> feat: 更新 @authing/spa-auth-sdk 包名为 @authing/browser

- docs/common/integrate-sso.md
- docs/en/common/integrate-sso.md
- 更新 SSO 示例代码地址；
- 更新  Authing Browser SDK 相关描述；
> feat: 更新 SSO 示例代码地址

- docs/.vuepress/theme/layouts/Layout.vue
> feat: 替换字符串

- docs/reference/guard/v3/mpa.md
- docs/reference/guard/v3/spa.md
> doc: udpate docs

- docs/reference/guard/v3/mpa.md
- docs/reference/guard/v3/spa.md
> fixed docs

- docs/.vuepress/theme/components/SearchInput.vue
> fix(searchinput): guard 搜索只展示 v3

- docs/tenant/reference/sdk-for-node/management/TenantManagementClient.md
> fix:缺陷需求:1212896

- docs/reference/sdk-for-weixin-miniapp.md
> chore: update

- docs/reference/sdk-for-weixin-miniapp.md
> fix(doc): adjust response types

- docs/common/integrate-sso.md
> feat: update sso docs

- docs/.vuepress/sidebar.js
> docs(js-sdk): adjust menu order

- docs/en/reference/sdk-for-android/social/alipay.md
- docs/en/reference/sdk-for-android/social/wechat.md
- docs/reference/sdk-for-android/social/alipay.md
- docs/reference/sdk-for-android/social/google.md
- docs/reference/sdk-for-android/social/lark.md
- docs/reference/sdk-for-android/social/oneauth.md
- docs/reference/sdk-for-android/social/wechat.md
- docs/reference/sdk-for-android/social/wecom.md
> fix: update social login documents

- docs/en/reference/sdk-for-android/social/alipay.md
- docs/en/reference/sdk-for-android/social/wechat.md
- docs/reference/sdk-for-android/social/alipay.md
- docs/reference/sdk-for-android/social/google.md
- docs/reference/sdk-for-android/social/lark.md
- docs/reference/sdk-for-android/social/oneauth.md
- docs/reference/sdk-for-android/social/wechat.md
- docs/reference/sdk-for-android/social/wecom.md
> fix: social login documents format

- docs/en/reference/sdk-for-android/apis/protocol/README.md
- docs/en/reference/sdk-for-android/social/wechat.md
- docs/reference/sdk-for-android/apis/protocol/README.md
- docs/reference/sdk-for-android/social/wechat.md
> feat: update apis document

- docs/integration/README.md
> feat: 订阅蜂上架

- docs/multi-tenant-console/tenant-management.md
> fix:租户管理引用文档跳转链接修改

- docs/reference/guard/v2/web.md
> doc: update web guard config

- docs/reference/guard/v2/web.md
> doc: update web guard, add after-change-module event

- docs/en/reference/sdk-for-ios/social/miniprogram.md
- docs/reference/sdk-for-ios/social/miniprogram.md
> Fix - wechat miniprogram docs

- docs/reference/guard/v2/web.md
> doc(web sdk): add config of style for web guard

- docs/reference/guard/v2/web.md
> fix web guard

- docs/reference/guard/v2/angular.md
- docs/reference/guard/v2/native-javascript.md
- docs/reference/guard/v2/react.md
- docs/reference/guard/v2/vue.md
> feat(guard): custom css

- docs/integration/teamviewer/0.md
> feat(teamview): 修改路径

- docs/en/reference/sdk-for-ios/social/line.md
- docs/reference/sdk-for-ios/scenario/otp.md
- docs/reference/sdk-for-ios/social/line.md
> Fix - mobile docs link error

- docs/en/reference/sdk-for-ios/social/line.md
- docs/reference/sdk-for-ios/scenario/README.md
- docs/reference/sdk-for-ios/scenario/otp.md
- docs/reference/sdk-for-ios/social/line.md
> Doc ios sdk

- docs/.vuepress/sidebar.js
> Fix - social connect added line-mobile

- docs/guides/connections/enterprise/lark-block/README.md
> fix: 替换正确的文件

- docs/guides/user/public-account.md
> Fix - public account docs

- docs/common/custom-password-script.md
> feat: zip 文件修改
